"""base de datos

Revision ID: 1b394e46c1c4
Revises: 
Create Date: 2026-05-19 17:47:45.868846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b394e46c1c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicos',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_medico')
    )
    op.create_table('pacientes',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('consultas',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=False),
    sa.Column('tratamiento', sa.Text(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medicos.id_medico'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultas')
    op.drop_table('usuarios')
    op.drop_table('pacientes')
    op.drop_table('medicos')
    # ### end Alembic commands ###
